name: ci-cd

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'   # Deploy on version tags if you prefer tag-driven prod

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --ci
      - run: npm run build
      # Add SAST/DAST, SBOM, license checks, etc.

  deploy-dev:
    needs: ci
    if: github.ref == 'refs/heads/develop'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: ./scripts/deploy.sh dev

  deploy-staging:
    needs: ci
    if: startsWith(github.ref, 'refs/heads/release/')
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: ./scripts/deploy.sh staging

  deploy-prod:
    needs: ci
    # Option A: main merges
    if: github.ref == 'refs/heads/main'
    # Option B: tag-based (uncomment instead)
    # if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: production
      url: https://your.prod.url
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: ./scripts/deploy.sh prod
