# Dockerfile for Deployment

# Use official Python image as base
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy project files to the container
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose API port
EXPOSE 5000

# Run the Flask API
CMD ["python", "route_optimization.py"]
